[package]
name = "react_compiler_oxc"
version = "0.1.0"
edition = "2024"

[dependencies]
react_compiler = { path = "../react_compiler" }
react_compiler_hir = { path = "../react_compiler_hir" }
react_compiler_reactive_scopes = { path = "../react_compiler_reactive_scopes" }
oxc_parser = "0.136.0"
oxc_ast = "0.136.0"
oxc_ast_visit = "0.136.0"
oxc_semantic = "0.136.0"
oxc_allocator = "0.136.0"
oxc_span = "0.136.0"
oxc_str = "0.136.0"
oxc_diagnostics = "0.136.0"
oxc_codegen = "0.136.0"
